services:
  ollama:
    container_name: ollama
    image: ollama/ollama  # Replace with specific Ollama version if needed
    environment:
      - OLLAMA_HOST=0.0.0.0  # Add your environment variable here
    ports:
      - "11434:11434"  # Map host port 11434 to container port 11434
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all  # Adjust count for the number of GPUs you want to use
    volumes:
      - ollama:/root/.ollama
    restart: always
volumes:
  ollama: